### ISSUE TITLE
Assign acronyms to the mappool

### ISSUE THREAD

**Issue by megahello** [wesley-221/wyReferee#20]
**Is your feature request related to a problem? Please describe.**
Sometimes the referee might not know which map is which and most players type for example "pick NM5" but to the referee it's displayed as a map name. Yes, you can add the mappool IDs in order but it would definitely make it easier. This will also help to reduce the size of the referee settings and fit smaller screens better. 

**Describe the solution you'd like**
Currently the mappool editor [looks like this](https://megahello.s-ul.eu/Wl766d0K). It would be nice to have a acronym part there which could be text shown in the referee settings to avoid less confusion. 
The acronym can also help reduce the width of the entire section by making the mod-pools to square selections. [Quick concept](https://megahello.s-ul.eu/DkFArAlx). Left click for red pick and Right click for blue click. Hold shift to ban instead. Ctrl to reset.
These squares can obviously be smaller so the entire parts width can be reduced. 

**Describe alternatives you've considered**
Separate mappool to a different sidebar.

**Comment by wesley-221** [comment]
Mod acronyms are actually a thing already: 
![](https://i.imgur.com/hDd1Xkc.png)

When you have entered a mod acronym for the mod bracket(s), it'll recognize <acronym><map index> (NM1/HD3/FM4/etc.) being typed in chat and it'll be clickable like so:
![](https://i.imgur.com/TGMlGpA.png)

As for changing the sidebar, will probably change it to look somewhat like your concept but with a ban/change picked by button attached to it
