### ISSUE TITLE
Can't open "Select a Tournament" dropdown

### ISSUE THREAD

**Issue by auroraongithub** [wesley-221/wyReferee#29]
**Describe the bug**
Can't open the "Select a Tournament" dropdown.

**To Reproduce**
Open lobby and try to select a tournament

**Expected behavior**
No dropdown shows

**Screenshots**
![image](https://user-images.githubusercontent.com/86182778/182053599-d3d6d300-abc6-46b5-87a7-ee1353849813.png)

**Comment by wesley-221** [comment]
Do you have any tournaments imported in your local tournaments (click on management > Tournament)? If not, you have to import a tournament or make one yourself

**Comment by auroraongithub** [comment]
no, but what you said does make sense, will try
