### ISSUE TITLE
"Incorrect Slot" Message Shows Up While Having the Condition Fulfilled

### ISSUE THREAD

**Issue by Dapuluous** [wesley-221/wyReferee#38]
**Describe the bug**
A message "Incorrect slot, player should be in slot x" while reffing shows up although the players have already in their reserved slot. It happens when I send "!mp settings" in multiplayer chat room.

**Expected behavior**
No "Incorrect slot" message within the multiplayer info settings when the players are in their reserved slot.

**Screenshots**
![wyReferee_LN9O09NLOA](https://user-images.githubusercontent.com/36445674/197186351-a1f54fbf-a9d6-498d-bad8-57f6e7a9d540.png)

**Comment by wesley-221** [comment]
Let me know if it
