### ISSUE TITLE
Can't scroll information page

### ISSUE THREAD

**Issue by JyJyJ4JyJ** [wesley-221/wyReferee#99]
As title says there's no way to scroll down information page. I know that making full screen allows to see all the information, but I don't think it's intuitively understandable for everyone (especially given the fact that app doesn't open in full screen by default) and anyway it looks strange that there's no such feature.

**To Reproduce**
1. Download the app
2. Install the app
3. Open the app
4. Go to the Information page
5. See described issue

**Expected behavior**
Can scroll down text on information page to see all the information with no need to go full screen.

**Screenshots**
![image](https://github.com/wesley-221/wyReferee/assets/54955042/3c4d97f9-c518-4d48-8405-16717e53d178)

**Additional context**
 - OS: Windows

**Comment by wesley-221** [comment]
Didn't know it didn't have a scrollbar, my client opens as a 1920x1080 so never noticed it myself, anyway should be fixed when I push the next update (should be after the weekend)
